# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a45069befba38ea44ed7a5b764260bec4e0d7fe4984cda3dd645efb82a44b7085e749183b5fb8724a55c652333ea0ac0dd0f6f7ca061bc63619ddc46288de77

test:
  secret_key_base: e31604328766bb1aab5b29fc1d3c8058b69d2ee414622bcb05335fb3aa3a9da295d9509c756681d33d0a9f4c6675cbff76785955569ccd6552befd4731bfc7fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
